# Generated by Django 5.0.3 on 2024-03-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_due_back_bookinstance_due_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='due_book',
            new_name='due_back',
        ),
    ]
